apiVersion: apps/v1
kind: Deployment
metadata:
  name: tmpmail-smtp-server
spec:
  replicas: 0
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: tmpmail-smtp-server
  template:
    metadata:
      labels:
        app: tmpmail-smtp-server
    spec:
      containers:
        - image: ghcr.io/hqhalo/tmpmail-smtp-server:latest
          name: tmpmail-smtp-server
          ports:
            - containerPort: 25
          env:
            - name: REDIS_HOST
              value: redis-0.redis.default.svc.k8s-dev-01.local
            - name: REDIS_PORT
              value: "6379"